-- apply changes
create table database_connection (
  id                            bigint generated by default as identity not null,
  sort                          bigint,
  database_type                 integer,
  host                          varchar(255),
  port                          integer,
  database                      varchar(255),
  username                      varchar(255),
  password                      varchar(255),
  create_at                     timestamp not null,
  update_at                     timestamp not null,
  constraint ck_database_connection_database_type check ( database_type in (0,1,2)),
  constraint pk_database_connection primary key (id)
);

create table history (
  id                            bigint generated by default as identity not null,
  sort                          bigint,
  path                          varchar(255),
  create_at                     timestamp not null,
  update_at                     timestamp not null,
  constraint pk_history primary key (id)
);

