plugins {
  jacoco
  java
  alias(libs.plugins.dotenv)
}
apply<IdeaSetting>()
apply<FormatSetting>()
apply<RepositoriesSetting>()
apply<JavaFxSetting>()
apply<AllProjectSetting>()
apply<RootProjectSetting>()
apply<ReleaseSetting>()

dependencies {
  compileOnly(projects.codegen.visualCodegen)
  annotationProcessor(projects.codegen.visualCodegen)
  implementation(libs.hikariCP)
  implementation(libs.jacksonCore)
  implementation(libs.jacksonDatabind)
  implementation(libs.jacksonAnnotations)
  implementation(libs.logback)
  implementation(libs.guice)
  implementation(libs.guiceJMX)
  implementation(libs.guiceGrapher)
  implementation(libs.avajeValidaor)
  annotationProcessor(libs.avajeValidaorCodegen)
  annotationProcessor(libs.picocliCodegen)
  implementation(libs.pcollections)
  implementation(libs.gestaltConfig)
  implementation(libs.gestaltToml)
  implementation(libs.gestaltGuice) {
    exclude(group = "com.google.guava", module = "guava")
  }
  testImplementation(libs.javafxUnitTest)
  annotationProcessor(libs.picocliCodegen)
  implementation(projects.ui.visualCollaborative)
  implementation(projects.ui.visualI18n)
  implementation(projects.module.visualGit)
  implementation(projects.module.visualShared)
  implementation(projects.ui.visualDebugger)
  implementation(projects.ui.visualComponent)
  implementation(projects.ui.visualGraphEditor)
  implementation(libs.guiceThrowingproviders)
  implementation(libs.guiceAssistedinject)
  implementation(projects.serialize.visualSerializeApi)
  implementation(projects.serialize.visualSerializeJson)
  implementation(libs.picocli)
  implementation(libs.picocliJline)
  implementation(projects.module.visualLocalStore)
  testImplementation(libs.guiceTestlib)
}