[package]
name = "Visual"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = { version = "0.30" }
eframe = { version = "0.30", features = ["wgpu"] }
serde = { version = "1", features = ["derive"] }
ron = "0.8"