/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MacThemeDetector */

#ifndef _Included_MacThemeDetector
#define _Included_MacThemeDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MacThemeDetector
 * Method:    getCurrentTheme
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MacThemeDetector_getCurrentTheme
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
