[versions]
jdk = "21"
kotlin = "1.9.22"
apacheCommonIO = "2.14.0"
directories = "26"
ikonliJavafx = "12.3.1"
slf4j = "2.1.0-alpha1"
javafx = "0.1.0"
freefairPlugin = "8.4"
logback = "1.4.7"
ikonli = "12.3.1"
groovy = "5.0.0-alpha-4"
javafxUnitTest = "4.0.17"
junit = "5.10.1"
testcontainers = "1.19.3"
junitPlatformSuite = "1.10.1"
jerbrainsAnnotation = "24.0.1"
mockito = "5.8.0"
caffine = "3.1.8"
dokka = "1.9.10"
spotless = "6.23.3"
gitVersion = "3.0.0"
jreleaser = "1.9.0"
antlr = "4.5"
koin = "3.5.3"
kotlinSerializationJson= "1.6.0"
kotlinCoroutines="1.8.0-RC2"

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx" }
sass = { id = "io.freefair.sass-java", version.ref = "freefairPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "freefairPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitVersion = { id = "com.palantir.git-version", version.ref = "gitVersion" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
koinBom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koinCore = { group = "io.insert-koin", name = "koin-core-jvm", version.ref = "koin" }
koinCoreCoroutines = { group = "io.insert-koin", name = "koin-core-coroutines", version.ref = "koin" }
koinTest = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koinSlf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
apacheCommonIO = { group = "commons-io", name = "commons-io", version.ref = "apacheCommonIO" }
directories = { group = "dev.dirs", name = "directories", version.ref = "directories" }
ikonliJavafx = { group = "org.kordamp.ikonli", name = "ikonli-javafx", version.ref = "ikonliJavafx" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
simpleicon = { group = "org.kordamp.ikonli", name = "ikonli-simpleicons-pack", version.ref = "ikonli" }
devicons = { group = "org.kordamp.ikonli", name = "ikonli-devicons-pack", version.ref = "ikonli" }
fontawesome5 = { group = "org.kordamp.ikonli", name = "ikonli-fontawesome5-pack", version.ref = "ikonli" }
groovy = { group = "org.apache.groovy", name = "groovy-all", version.ref = "groovy" }
javafxUnitTest = { group = "org.testfx", name = "testfx-junit5", version.ref = "javafxUnitTest" }
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junitJuiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitPlatformSuite = { group = "org.junit.platform", name = "junit-platform-suite", version.ref = "junitPlatformSuite" }
testcontainersBom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainersJunit = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }
testcontainersMinio = { group = "org.testcontainers", name = "minio", version.ref = "testcontainers" }
jetbrainsAnnotation = { group = "org.jetbrains", name = "annotations", version.ref = "jerbrainsAnnotation" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoJunit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
caffine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffine" }
antlr = { group = "org.antlr", name = "antlr4", version.ref = "antlr" }
kotlinSerializationJson = {group="org.jetbrains.kotlinx",name="kotlinx-serialization-json",version.ref="kotlinSerializationJson"}
kotlinCoroutines={group="org.jetbrains.kotlinx",name="kotlinx-coroutines-core",version.ref="kotlinCoroutines"}