[versions]
jdk = "21"
apacheCommonIO = "2.14.0"
kotlin = "2.0.0-Beta2"
directories = "26"
ikonliJavafx = "12.3.1"
slf4j = "2.1.0-alpha1"
javafx = "0.1.0"
freefairPlugin = "8.4"
logback = "1.4.7"
ikonli = "12.3.1"
groovy = "5.0.0-alpha-4"
javafxUnitTest = "4.0.17"
junit = "5.10.1"
testcontainers = "1.19.3"
junitPlatformSuite = "1.10.1"
jerbrainsAnnotation = "24.0.1"
mockito = "5.8.0"
caffine = "3.1.8"
dokka = "1.9.10"
spotless = "6.23.3"
gitVersion = "3.0.0"
jreleaser = "1.9.0"
antlr = "4.5"
oshi = "6.4.10"
avajeInject = "9.10"
guice = "7.0.0"
apacheCommonLang3 = "3.14.0"
gestalt = "0.24.3"
guava = "33.0.0-jre"
plantuml = "2.1.3"
mavenResolver="2.0.0-alpha-6"

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx" }
sass = { id = "io.freefair.sass-java", version.ref = "freefairPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "freefairPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitVersion = { id = "com.palantir.git-version", version.ref = "gitVersion" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
plantuml = { id = "io.gitlab.plunts.plantuml", version.ref = "plantuml" }

[libraries]
apacheCommonIO = { group = "commons-io", name = "commons-io", version.ref = "apacheCommonIO" }
apacheCommonLang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonLang3" }
directories = { group = "dev.dirs", name = "directories", version.ref = "directories" }
ikonliJavafx = { group = "org.kordamp.ikonli", name = "ikonli-javafx", version.ref = "ikonliJavafx" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4jJdkPlatform = { group = "org.slf4j", name = "slf4j-jdk-platform-logging", version.ref = "slf4j" }
oshi = { group = "com.github.oshi", name = "oshi-core-java11", version.ref = "oshi" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
simpleicon = { group = "org.kordamp.ikonli", name = "ikonli-simpleicons-pack", version.ref = "ikonli" }
fluentuiIcon = { group = "org.kordamp.ikonli", name = "ikonli-fluentui-pack", version.ref = "ikonli" }
devicons = { group = "org.kordamp.ikonli", name = "ikonli-devicons-pack", version.ref = "ikonli" }
fontawesome5 = { group = "org.kordamp.ikonli", name = "ikonli-fontawesome5-pack", version.ref = "ikonli" }
groovy = { group = "org.apache.groovy", name = "groovy-all", version.ref = "groovy" }
javafxUnitTest = { group = "org.testfx", name = "testfx-junit5", version.ref = "javafxUnitTest" }
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junitJuiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitPlatformSuite = { group = "org.junit.platform", name = "junit-platform-suite", version.ref = "junitPlatformSuite" }
testcontainersBom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainersJunit = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }
testcontainersMinio = { group = "org.testcontainers", name = "minio", version.ref = "testcontainers" }
jetbrainsAnnotation = { group = "org.jetbrains", name = "annotations", version.ref = "jerbrainsAnnotation" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoJunit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
caffine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffine" }
antlr = { group = "org.antlr", name = "antlr4", version.ref = "antlr" }
avajeInject = { group = "io.avaje", name = "avaje-inject", version.ref = "avajeInject" }
avajeInjectGenerator = { group = "io.avaje", name = "avaje-inject-generator", version.ref = "avajeInject" }
avajeInjectTest = { group = "io.avaje", name = "avaje-inject", version.ref = "avajeInject" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
guiceAssistedinject = { group = "com.google.inject.extensions", name = "guice-assistedinject", version.ref = "guice" }
guiceThrowingproviders = { group = "com.google.inject.extensions", name = "guice-throwingproviders", version.ref = "guice" }
guiceTestlib = { group = "com.google.inject.extensions", name = "guice-testlib", version.ref = "guice" }
gestaltConfig = { group = "com.github.gestalt-config", name = "gestalt-core", version.ref = "gestalt" }
gestaltToml = { group = "com.github.gestalt-config", name = "gestalt-toml", version.ref = "gestalt" }
gestaltGuice = { group = "com.github.gestalt-config", name = "gestalt-guice", version.ref = "gestalt" }
gestaltKotlin = { group = "com.github.gestalt-config", name = "gestalt-kotlin", version.ref = "gestalt" }
gestaltGit = { group = "com.github.gestalt-config", name = "gestalt-git", version.ref = "gestalt" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinGradleLombokPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-lombok", version.ref = "kotlin" }
kotlinGradleSerializationPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
kotlinGradleNoArgPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-noarg", version.ref = "kotlin" }
kotlinGradleAllOpenPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-allopen", version.ref = "kotlin" }
kotlinGradleSpringPlugin = { group = "org.jetbrains.kotlin.plugin.spring", name = "org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
mavenResloverAPI= {group="org.apache.maven.resolver",name="maven-resolver-api",version.ref="mavenResolver"}
mavenResloverImpl= {group="org.apache.maven.resolver",name="maven-resolver-impl",version.ref="mavenResolver"}
mavenResloverJDK21= {group="org.apache.maven.resolver",name="maven-resolver-transport-jdk",version.ref="mavenResolver"}
mavenResloverUtil= {group="org.apache.maven.resolver",name="maven-resolver-util",version.ref="mavenResolver"}
mavenResloverSupplier= {group="org.apache.maven.resolver",name="maven-resolver-supplier",version.ref="mavenResolver"}