[versions]
jdk = "21"
ikonliJavafx = "12.3.1"
slf4j = "2.1.0-alpha1"
freefairPlugin = "8.6"
ikonli = "12.3.1"
junit = "5.10.2"
testcontainers = "1.19.7"
mockito = "5.11.0"
avajeInject = "9.11"
gestalt = "0.24.6"
mavenResolver = "2.0.0-alpha-8"
javafxVersion = "21.0.2"
eclipseCollections = "12.0.0.M3"
avajeConfig = "3.10"
jackson = "2.17.0-rc1"
picocli = "4.7.5"
mapstruct = "1.6.0.Beta1"
jgit = "6.9.0.202403050737-r"
vertx = "4.5.4"
guice = "7.0.0"
jdbi = "3.45.0"
hibernate = "6.4.4.Final"

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
lombok = { id = "io.freefair.lombok", version.ref = "freefairPlugin" }
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
fatjar = { id = "io.github.goooler.shadow", version = "8.1.7" }
frontend = { id = "org.siouan.frontend-jdk17", version = "8.0.0" }
versionCheck = { id = "com.github.ben-manes.versions", version = "0.51.0" }
javamodularity = { id = "org.javamodularity.moduleplugin", version = "1.8.14" }
sass = { id = "io.miret.etienne.sass", version = "1.5.0" }
hibernate = { id = "org.hibernate.orm", version.ref = "hibernate" }
extraJavaModule = { id = "org.gradlex.extra-java-module-info", version = "1.8" }

[libraries]
apacheCommonIO = { group = "commons-io", name = "commons-io", version = "2.14.0" }
apacheCommonLang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.14.0" }
apacheCommonPool = { group = "org.apache.commons", name = "commons-pool2", version = "2.12.0" }
directories = { group = "dev.dirs", name = "directories", version = "26" }
ikonliJavafx = { group = "org.kordamp.ikonli", name = "ikonli-javafx", version.ref = "ikonliJavafx" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4jJdkPlatform = { group = "org.slf4j", name = "slf4j-jdk-platform-logging", version.ref = "slf4j" }
oshi = { group = "com.github.oshi", name = "oshi-core-java11", version = "6.4.13" }
logback = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.3" }
simpleicon = { group = "org.kordamp.ikonli", name = "ikonli-simpleicons-pack", version.ref = "ikonli" }
fluentuiIcon = { group = "org.kordamp.ikonli", name = "ikonli-fluentui-pack", version.ref = "ikonli" }
devicons = { group = "org.kordamp.ikonli", name = "ikonli-devicons-pack", version.ref = "ikonli" }
materialIcons = { group = "org.kordamp.ikonli", name = "ikonli-materialdesign2-pack", version.ref = "ikonli" }
fontawesome5 = { group = "org.kordamp.ikonli", name = "ikonli-fontawesome5-pack", version.ref = "ikonli" }
groovy = { group = "org.apache.groovy", name = "groovy-all", version = "5.0.0-alpha-4" }
javafxUnitTest = { group = "org.testfx", name = "testfx-junit5", version = "4.0.18" }
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junitJuiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitPlatformSuite = { group = "org.junit.platform", name = "junit-platform-suite", version = "1.10.2" }
testcontainersBom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainersJunit = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }
testcontainersMysql = { group = "org.testcontainers", name = "mysql", version.ref = "testcontainers" }
testcontainersMssqlserver = { group = "org.testcontainers", name = "mssqlserver", version.ref = "testcontainers" }
testcontainersPostgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
jetbrainsAnnotation = { group = "org.jetbrains", name = "annotations", version = "24.1.0" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoJunit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
caffine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version = "3.1.8" }
antlr = { group = "org.antlr", name = "antlr4", version = "4.13.1" }
avajeInject = { group = "io.avaje", name = "avaje-inject", version.ref = "avajeInject" }
avajeInjectGenerator = { group = "io.avaje", name = "avaje-inject-generator", version.ref = "avajeInject" }
avajeInjectTest = { group = "io.avaje", name = "avaje-inject", version.ref = "avajeInject" }
gestaltConfig = { group = "com.github.gestalt-config", name = "gestalt-core", version.ref = "gestalt" }
gestaltToml = { group = "com.github.gestalt-config", name = "gestalt-toml", version.ref = "gestalt" }
gestaltGit = { group = "com.github.gestalt-config", name = "gestalt-git", version.ref = "gestalt" }
gestaltGuice = { group = "com.github.gestalt-config", name = "gestalt-guice", version.ref = "gestalt" }
guava = { group = "com.google.guava", name = "guava", version = "33.0.0-jre" }
mavenResloverAPI = { group = "org.apache.maven.resolver", name = "maven-resolver-api", version.ref = "mavenResolver" }
mavenResloverImpl = { group = "org.apache.maven.resolver", name = "maven-resolver-impl", version.ref = "mavenResolver" }
mavenResloverJDK21 = { group = "org.apache.maven.resolver", name = "maven-resolver-transport-jdk", version.ref = "mavenResolver" }
mavenResloverUtil = { group = "org.apache.maven.resolver", name = "maven-resolver-util", version.ref = "mavenResolver" }
mavenResloverSupplier = { group = "org.apache.maven.resolver", name = "maven-resolver-supplier", version.ref = "mavenResolver" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version = "8.3.0" }
postgres = { group = "org.postgresql", name = "postgresql", version = "42.7.2" }
mssql = { group = "com.microsoft.sqlserver", name = "mssql-jdbc", version = "12.6.1.jre11" }
h2 = { group = "com.h2database", name = "h2", version = "2.2.224" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version = "3.45.1.0" }
eclipseCollectionsAPI = { group = "org.eclipse.collections", name = "eclipse-collections-api", version.ref = "eclipseCollections" }
eclipseCollections = { group = "org.eclipse.collections", name = "eclipse-collections", version.ref = "eclipseCollections" }
eclipseCollectionsForkjoin = { group = "org.eclipse.collections", name = "eclipse-collections-forkjoin", version.ref = "eclipseCollections" }
eclipseCollectionsTestUtil = { group = "org.eclipse.collections", name = "eclipse-collections-testutils", version.ref = "eclipseCollections" }
jgrapht = { group = "org.jgrapht", name = "jgrapht-core", version = "1.5.2" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version = "8.5.13" }
hikariCP = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0" }
pcollections = { group = "org.pcollections", name = "pcollections", version = "4.0.1" }
avajeConfig = { group = "io.avaje", name = "avaje-config", version.ref = "avajeConfig" }
jacksonCore = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jacksonDatabind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jacksonAnnotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jacksonDataTypeEclipseCollection = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-eclipse-collections", version.ref = "jackson" }
jacksonDataTypeGuava = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-guava", version.ref = "jackson" }
jacksonDataTypePCollection = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-pcollections", version.ref = "jackson" }
jacksonDataTypeJsonP = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jakarta-jsonp", version.ref = "jackson" }
jacksonDataTypeXML = { group = "com.fasterxml.jackson.datatype", name = "jackson-dataformat-xml", version.ref = "jackson" }
jacksonJrAll = { group = "com.fasterxml.jackson.jr", name = "jackson-jr-all", version.ref = "jackson" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
picocliJline = { group = "info.picocli", name = "picocli-shell-jline3", version.ref = "picocli" }
picocliCodegen = { group = "info.picocli", name = "picocli-codegen", version.ref = "picocli" }
avajeValidaor = { group = "io.avaje", name = "avaje-validator-constraints", version = "1.3" }
avajeValidaorCodegen = { group = "io.avaje", name = "avaje-validator-generator", version = "1.3" }
atlantafx = { group = "io.github.mkpaz", name = "atlantafx-base", version = "2.0.1" }
controlfx = { group = "org.controlsfx", name = "controlsfx", version = "11.2.0" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstructProcessor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombokMapstructBinding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version = "0.2.0" }
animated = { group = "eu.iamgio", name = "animated", version = "1.3.0" }
flowless = { group = "org.fxmisc.flowless", name = "flowless", version = "0.7.2" }
autoService = { group = "com.google.auto.service", name = "auto-service", version = "1.1.1" }
junitPerf = { group = "com.github.noconnor", name = "junitperf-junit5", version = "1.35.0" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgitJunit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.junit", version.ref = "jgit" }
jgitLfs = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.lfs", version.ref = "jgit" }
jgitSSH = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.ssh.apache", version.ref = "jgit" }
jgitHttp = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.http.apache", version.ref = "jgit" }
plantuml = { group = "net.sourceforge.plantuml", name = "plantuml-mit", version = "1.2024.3" }

vertxCore = { group = "io.vertx", name = "vertx-core", version.ref = "vertx" }
vertxJunit5 = { group = "io.vertx", name = "vertx-junit5", version.ref = "vertx" }
vertxHazelcast = { group = "io.vertx", name = "vertx-hazelcast", version.ref = "vertx" }
vertxWeb = { group = "io.vertx", name = "vertx-web", version.ref = "vertx" }
vertxPostgresqlClient = { group = "io.vertx", name = "vertx-pg-client", version.ref = "vertx" }
vertxMySQLClient = { group = "io.vertx", name = "vertx-mysql-client", version.ref = "vertx" }
vertxDB2Client = { group = "io.vertx", name = "vertx-db2-client", version.ref = "vertx" }
vertxOrcaleClient = { group = "io.vertx", name = "vertx-oracle-client", version.ref = "vertx" }
vertxMssqlClient = { group = "io.vertx", name = "vertx-mssql-client", version.ref = "vertx" }
vertxSqlClientTemplate = { group = "io.vertx", name = "vertx-sql-client-templates", version.ref = "vertx" }
vertxMongoDBClient = { group = "io.vertx", name = "vertx-mongo-client", version.ref = "vertx" }
vertxRedisClient = { group = "io.vertx", name = "vertx-redis-client", version.ref = "vertx" }
vertxCassandraClient = { group = "io.vertx", name = "vertx-cassandra-client", version.ref = "vertx" }
vertxJdbcClient = { group = "io.vertx", name = "vertx-jdbc-client", version.ref = "vertx" }
vertxKafkaClient = { group = "io.vertx", name = "vertx-kafka-client", version.ref = "vertx" }
vertxAMQPClient = { group = "io.vertx", name = "vertx-amqp-client", version.ref = "vertx" }
vertxRabbitmqClient = { group = "io.vertx", name = "vertx-rabbitmq-client", version.ref = "vertx" }
vertxMQTTClient = { group = "io.vertx", name = "vertx-mqtt", version.ref = "vertx" }
vertxURLTemplate = { group = "io.vertx", name = "vertx-uri-template", version.ref = "vertx" }

apacheDBUtil = { group = "commons-dbutils", name = "commons-dbutils", version = "1.8.1" }

bytebuddy = { group = "net.bytebuddy", name = "byte-buddy", version = "1.14.12" }
preferencesfx = { group = "com.dlsc.preferencesfx", name = "preferencesfx-core", version = "11.17.0" }

guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
jSystemThemeDetector = { group = "com.github.Dansoftowner", name = "jSystemThemeDetector", version = "3.8" }
jsqlparser = { group = "com.github.jsqlparser", name = "jsqlparser", version = "4.9" }
immutable = { group = "org.immutables", name = "value", version = "2.10.1" }

jdbiCore = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi" }
pf4j = { group = "org.pf4j", name = "pf4j", version = "3.10.0" }
mutiny = { group = "io.smallrye.reactive", name = "mutiny", version = "2.5.8" }
mutinyVertx = { group = "io.smallrye.reactive", name = "smallrye-mutiny-vertx-core", version = "3.10.0" }
javapoet = { group = "com.squareup", name = "javapoet", version = "1.13.0" }

hibernatePlatform = { group = "org.hibernate.orm", name = "hibernate-platform", version.ref = "hibernate" }
hibernateCore = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernate" }
hibernateJpamodelgen = { group = "org.hibernate.orm", name = "hibernate-jpamodelgen", version.ref = "hibernate" }
hibernateValidator = { group = "org.hibernate.validator", name = "hibernate-validator", version = "8.0.1.Final" }
hibernateHikaricp = { group = "org.hibernate.orm", name = "hibernate-hikaricp", version.ref = "hibernate" }
hibernateTesting = { group = "org.hibernate.orm", name = "hibernate-testing", version.ref = "hibernate" }
hibernateGraalvm = { group = "org.hibernate.orm", name = "hibernate-graalvm", version.ref = "hibernate" }
hibernateJfr = { group = "org.hibernate.orm", name = "hibernate-jfr", version.ref = "hibernate" }
jakartaPersistenceAPI = { group = "jakarta.persistence", name = "jakarta.persistence-api", version = "3.2.0-M2" }


#Plugins
spotlessPlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "6.25.0" }
javaFxPlugin = { group = "org.openjfx.javafxplugin", name = "org.openjfx.javafxplugin.gradle.plugin", version = "0.1.0" }
lombokPlugin = { group = "name.remal.gradle-plugins.lombok", name = "lombok", version = "2.2.4" }
plantumlPlugin = { group = "io.gitlab.plunts", name = "plantuml-gradle-plugin", version = "2.1.6" }
dokkaPlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version = "1.9.20" }
manifestPlugin = { group = "com.coditory.gradle", name = "manifest-plugin", version = "0.2.6" }
semverPlugin = { group = "com.xenoterracide", name = "gradle-semver", version = "0.9.7" }
versionCheckPlugin = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version = "0.51.0" }
dependencycheckPlugin = { group = "org.owasp", name = "dependency-check-gradle", version = "9.0.9" }
jreleaserPlugin = { group = "org.jreleaser", name = "jreleaser-gradle-plugin", version = "1.1.0" }
jmhPlugin = { group = "me.champeau.jmh", name = "jmh-gradle-plugin", version = "0.7.2" }
spotbugsPlugin = { group = "com.github.spotbugs.snom", name = "spotbugs-gradle-plugin", version = "6.0.8" }
graalvmPlugin = { group = "org.graalvm.buildtools", name = "native-gradle-plugin", version = "0.10.1" }
jlinkPlugin = { group = "org.beryx", name = "badass-jlink-plugin", version = "3.0.1" }
fatjarPlugin = { group = "io.github.goooler.shadow", name = "shadow-gradle-plugin", version = "8.1.7" }
