module org.visual.model.ui {
    requires transitive javafx.graphics;
    requires transitive javafx.controls;
    requires transitive javafx.fxml;
    requires static lombok;
    requires org.slf4j;
    requires com.google.common;
    requires com.github.oshi;
    requires org.jetbrains.annotations;
    requires transitive org.kordamp.ikonli.core;
    requires transitive org.kordamp.ikonli.javafx;
    requires transitive org.kordamp.ikonli.fontawesome5;
    requires transitive org.kordamp.ikonli.fluentui;
    requires transitive org.kordamp.ikonli.simpleicons;
    requires transitive org.kordamp.ikonli.devicons;
    requires transitive org.kordamp.ikonli.materialdesign2;
    requires org.visual.model.shared;
    requires org.apache.commons.lang3;
    requires transitive atlantafx.base;
    requires static com.sun.jna;
    requires org.visual.model.jfa;
    requires static com.sun.jna.platform;
    requires transitive org.controlsfx.controls;
    requires eu.iamgio.animated;
    requires kotlin.stdlib;
    requires org.apache.commons.pool2;
    requires it.unimi.dsi.fastutil;
    requires com.github.kwhat.jnativehook;
    requires javafx.media;
    requires javafx.swing;
    requires org.visual.model.component.annotation;
    requires com.google.auto.service;

    exports org.visual.model.component.title;
    exports org.visual.model.component.window;
    exports org.visual.model.component.layout;
    exports org.visual.model.component.control;
    exports org.visual.model.component.control.click;
    exports org.visual.model.component.control.button;
    exports org.visual.model.component.control.dialog;
    exports org.visual.model.component.control.drag;
    exports org.visual.model.component.control.scroll;
    exports org.visual.model.component.control.globalscreen;
    exports org.visual.model.component.util;
    exports org.visual.model.component.theme;
    exports org.visual.model.component.container;
    exports org.visual.model.component.widget;
    exports org.visual.model.component.animation;
    exports org.visual.model.component.api;
    exports org.visual.model.component.display;
    exports org.visual.model.component.wrapper;

    opens org.visual.model.component.theme to com.sun.jna;
    opens org.visual.model.component.title to javafx.graphics, javafx.fxml;
    opens org.visual.model.component.window to javafx.graphics, javafx.fxml;
    opens org.visual.model.component.layout to javafx.graphics, javafx.fxml;
    opens org.visual.model.component.control to javafx.graphics, javafx.fxml;
    opens org.visual.model.component.container to javafx.fxml, javafx.graphics;
}
